{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.5.1.aar",
          "url": "navigation-fragment-2.5.1.aar",
          "size": 67712,
          "sha512": "5a7561b76542903adf782313408ace2496ff556db0c14ef8f69c937de87c7d88f0390e822e1881a1b8c56727c5402efb5ed09752d9edcc983883d0feb7d3b39a",
          "sha256": "ae109f7737f4318853d5232021301cb17e80f3fb3897010aa59d61fb92150cdd",
          "sha1": "f8256f8b42385ba8f469d25c7d5981914f2e6caf",
          "md5": "53235d48a7791d71c5ee1786cf3ce21a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.slidingpanelayout",
          "module": "slidingpanelayout",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.5.1.aar",
          "url": "navigation-fragment-2.5.1.aar",
          "size": 67712,
          "sha512": "5a7561b76542903adf782313408ace2496ff556db0c14ef8f69c937de87c7d88f0390e822e1881a1b8c56727c5402efb5ed09752d9edcc983883d0feb7d3b39a",
          "sha256": "ae109f7737f4318853d5232021301cb17e80f3fb3897010aa59d61fb92150cdd",
          "sha1": "f8256f8b42385ba8f469d25c7d5981914f2e6caf",
          "md5": "53235d48a7791d71c5ee1786cf3ce21a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-fragment-2.5.1-sources.jar",
          "url": "navigation-fragment-2.5.1-sources.jar",
          "size": 24003,
          "sha512": "d0327876bb22f0951c353dcbfe2bc42769899f2c3e6838e58a91ca86b2c7cbef4f1468d7b7568ae25a3d157347f7cf02c8e4082e8150484abbc8020ecc34f18e",
          "sha256": "1d03fa06379629e25c3f5ac5dd50c35063b4767b8ed35495408233aeb11cd915",
          "sha1": "8d901ab79e496cbab76b148a57727938406fe19e",
          "md5": "d7cc7de317ffe33443400511be09d2e5"
        }
      ]
    }
  ]
}