{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.4.1.aar",
          "url": "lifecycle-runtime-2.4.1.aar",
          "size": 11483,
          "sha512": "07d83a23c080b3541ab4afa1ab7e1b11785ace7070a944f94513de07832e493c89d7e251e754765a543b9ffd49a3e65c5042802951c64a90cb947bb0aa35f5c1",
          "sha256": "ba283298fc7d3d170f5676ef152a72e3c1566d5b46b3eadd7f55b90c3b54df60",
          "sha1": "5091ed6ca0f0274035de2d41621fe4c0b512d695",
          "md5": "cc2362695d33239f66f3ca021d66fe22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-2.4.1.aar",
          "url": "lifecycle-runtime-2.4.1.aar",
          "size": 11483,
          "sha512": "07d83a23c080b3541ab4afa1ab7e1b11785ace7070a944f94513de07832e493c89d7e251e754765a543b9ffd49a3e65c5042802951c64a90cb947bb0aa35f5c1",
          "sha256": "ba283298fc7d3d170f5676ef152a72e3c1566d5b46b3eadd7f55b90c3b54df60",
          "sha1": "5091ed6ca0f0274035de2d41621fe4c0b512d695",
          "md5": "cc2362695d33239f66f3ca021d66fe22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-runtime-2.4.1-sources.jar",
          "url": "lifecycle-runtime-2.4.1-sources.jar",
          "size": 8927,
          "sha512": "3a9f03beaffff0b273188c91a18f234962052eed4257f5b18b5098d09e2ed9799e3870b5b8cc63eeb429f03ef294f3109365c794bb84b11742048d1a1a0a4288",
          "sha256": "a1757f478939a9ae47e3a005f5c3ce051e50859d54478e3b931fdb06738269a9",
          "sha1": "ae7040cf314de81d20ac69f28f5ab6c9a2c0d1ab",
          "md5": "a34ad95ef12973e07a73efde45a2504e"
        }
      ]
    }
  ]
}
