{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.5.1.aar",
          "url": "navigation-ui-2.5.1.aar",
          "size": 94732,
          "sha512": "61bb253b68d56fce544cf7af38e31d8511b11737d61e3f4be780c68208d874e86c929d06d9a9b2394a052982b00c70a4a0fb65c8e4aed3ae23f6629b1c59f376",
          "sha256": "c308e47af98db1739f156adda4b3af3846963882f0155616de0882e3bf6dd434",
          "sha1": "83f1520900d97f9e23816906171ad94bd5563775",
          "md5": "e350c05254afe172f86515442610d8d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.5.1.aar",
          "url": "navigation-ui-2.5.1.aar",
          "size": 94732,
          "sha512": "61bb253b68d56fce544cf7af38e31d8511b11737d61e3f4be780c68208d874e86c929d06d9a9b2394a052982b00c70a4a0fb65c8e4aed3ae23f6629b1c59f376",
          "sha256": "c308e47af98db1739f156adda4b3af3846963882f0155616de0882e3bf6dd434",
          "sha1": "83f1520900d97f9e23816906171ad94bd5563775",
          "md5": "e350c05254afe172f86515442610d8d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-2.5.1-sources.jar",
          "url": "navigation-ui-2.5.1-sources.jar",
          "size": 20686,
          "sha512": "5f4036f284f005251437efd6ad229fc6bb7fa228b78fed88d70f2bab45de2a7674cfc9f2e180b5c5ae5737515fdfa8bd97e33bedd5b95633be9e4c6afd52db81",
          "sha256": "c4f794e33339583085d982c84e06ea102c33a103f4fc600e1897010c2c12ba93",
          "sha1": "31eb56e9799d9fc45ece9ee154e0b303a7797537",
          "md5": "4a4ec7f9d106c59adbdb51493ee05801"
        }
      ]
    }
  ]
}